services:
  web:
    container_name: web
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/:/home/web/app
    ports:
      - "8000:8000"
    env_file:
      - .env
